[project]
name = "nih-clinicaltrials-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "curl-cffi>=0.14.0",
    "fastmcp>=3.0.2",
    "httpx>=0.28.1",
]

[tool.setuptools.packages.find]
where = ["src"]
